export type Severity = 'PASSABLE' | 'MINOR' | 'MODERATE' | 'SEVERE'
export type ReportStatus = 'UNVERIFIED' | 'UNDER_REVIEW' | 'CONFIRMED'
export type Report = { id:string; lat:number; lng:number; severity:Severity; description:string; status:ReportStatus; confidence:number; upvoteCount:number; createdAt:string; handle:string; origin:'COMMUNITY'; area:string; photoUrl?:string }
export type OfficialAdvisory = { id:string; title:string; body:string; issuingAgency:string; issuedAt:string; region:string; provenanceUrl:string; origin:'OFFICIAL' }
export const severityMeta: Record<Severity,{label:string;color:string;depth:string}> = { PASSABLE:{label:'Passable',color:'#87CEEB',depth:'Ankle-deep'}, MINOR:{label:'Minor',color:'#2255CC',depth:'Knee-deep'}, MODERATE:{label:'Moderate',color:'#FF6B35',depth:'Waist-deep'}, SEVERE:{label:'Severe',color:'#E5383B',depth:'Chest-deep'} }
export const statusMeta: Record<ReportStatus,{label:string;color:string}> = { UNVERIFIED:{label:'Unverified',color:'#888'}, UNDER_REVIEW:{label:'Under review',color:'#87CEEB'}, CONFIRMED:{label:'Community · Confirmed',color:'#2255CC'} }
const MOCK_NOW = Date.parse('2026-10-03T16:40:00.000Z')
export function timeAgo(iso:string){const m=Math.max(1,Math.floor((MOCK_NOW-new Date(iso).getTime())/60000)); return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`}
export function clamp(n:number,min=0,max=1){return Math.min(max,Math.max(min,n))}
export function countCorroborating(report:Report, all:Report[]){return all.filter(r=>r.id!==report.id && Math.abs(r.lat-report.lat)<.005 && Math.abs(r.lng-report.lng)<.005 && MOCK_NOW-new Date(r.createdAt).getTime()<7200000).length}
export function deriveStatus(r:{upvoteCount:number;corroboratingNearby:number;ageMinutes:number}){const confidence=clamp((.15*r.upvoteCount+.25*r.corroboratingNearby)*Math.max(0,1-r.ageMinutes/360)); const status:ReportStatus=confidence>=.6&&r.corroboratingNearby>=2?'CONFIRMED':confidence>=.3||r.upvoteCount>=3?'UNDER_REVIEW':'UNVERIFIED'; return {status,confidence}}
const locations=[['Marikina River',14.633,121.101,'Waist-deep water along the riverbank near the market. Buses are stalled at the bridge.'],['Aurora Boulevard',14.619,121.056,'Water is pooling across two lanes near the intersection; motorcycles are turning back.'],['España Boulevard',14.609,120.994,'Knee-deep flooding is blocking the curb lane outside the university gates.'],['Pasig River Road',14.576,121.085,'Fast-rising water is covering the service road beside the river.'],['Taguig Creek',14.517,121.05,'Floodwater has entered the lower streets near the creek; residents are moving upstairs.'],['Commonwealth Avenue',14.676,121.043,'Heavy rain is reducing visibility and water is collecting near the footbridge.'],['Valenzuela Road',14.7,120.98,'Flooding is reported beside the public market, with traffic diverted to the next block.']] as const
const descriptions=['Waist-deep water along the riverbank near the market. Buses are stalled at the bridge.','Water is pooling across two lanes near the intersection; motorcycles are turning back.','Knee-deep flooding is blocking the curb lane outside the university gates.','Fast-rising water is covering the service road beside the river.','Floodwater has entered the lower streets near the creek; residents are moving upstairs.','Heavy rain is reducing visibility and water is collecting near the footbridge.','Flooding is reported beside the public market, with traffic diverted to the next block.','A blocked drain is pushing brown water across the residential lane.','Vehicles are moving slowly through ankle-deep water beside the station.','Residents placed warning tape around a submerged sidewalk opening.','Water is collecting outside the clinic entrance; keep children away from the curb.','A low section of road is impassable for tricycles and small cars.','Rainwater is flowing quickly downhill toward the homes at the corner.','The underpass is flooded and pedestrians are using the elevated walkway.','Several shops have raised their shutters as water reaches the doorway.','A fallen branch is slowing traffic where the flooded street narrows.','The footpath is underwater, but the main road remains passable with caution.','Water is surrounding parked vehicles near the terminal; avoid the side street.','A drainage grate is overflowing beside the school fence.','Floodwater is ankle-deep at the crossing and rising after another downpour.','Neighbors are checking on ground-floor households near the creek.','A bus route is delayed because the curb lane is covered in water.','The road remains open, but visibility is poor and puddles are deep.','Water has reached the first step of several homes along the alley.','Residents report a strong current near the canal; do not attempt to cross.','A shallow sheet of water covers the market entrance and nearby loading area.','Flooding is easing slowly, though debris remains across the shoulder.','The barangay road is wet and slick with standing water near the bend.']
export const mockReports:Report[]=Array.from({length:28},(_,i)=>{const [area,lat,lng]=locations[i%locations.length]; const severity:Severity=(['PASSABLE','MINOR','MODERATE','SEVERE'] as Severity[])[i%4]; const mins=5+i*9; return {id:`r-${i}`,lat:lat+(i%3-.9)*.006,lng:lng+((i*7)%3-1)*.006,severity,description:descriptions[i],status:i%5===0?'CONFIRMED':i%3===0?'UNDER_REVIEW':'UNVERIFIED',confidence:i%5===0?.72:i%3===0?.38:.12,upvoteCount:i%13,createdAt:new Date(MOCK_NOW-mins*60000).toISOString(),handle:`Resident-${(0x4f2a+i*137).toString(16).toUpperCase()}`,origin:'COMMUNITY',area}})
export const mockAdvisories:OfficialAdvisory[]=[{id:'a1',title:'Heavy Rainfall Warning · Orange Level',body:'Intense rainfall is expected across Metro Manila. Flooding is threatening in low-lying areas.',issuingAgency:'PAGASA',issuedAt:'25 minutes ago',region:'National Capital Region',provenanceUrl:'https://bagong.pagasa.dost.gov.ph',origin:'OFFICIAL'},{id:'a2',title:'Flood Advisory · Marikina River',body:'River levels are being monitored. Residents near waterways should stay alert and prepare to evacuate.',issuingAgency:'NDRRMC',issuedAt:'1 hour ago',region:'Marikina',provenanceUrl:'https://ndrrmc.gov.ph',origin:'OFFICIAL'},{id:'a3',title:'Flood Control Update',body:'MMDA teams are deployed at known flood-prone corridors. Expect intermittent road closures.',issuingAgency:'MMDA',issuedAt:'2 hours ago',region:'Metro Manila',provenanceUrl:'https://mmda.gov.ph',origin:'OFFICIAL'}]
export const reportsById=(id:string)=>mockReports.find(r=>r.id===id)
export function clusterReports(reports:Report[],zoom:number){const cell=zoom<=10?.04:zoom<=12?.02:zoom<=14?.01:.005; const map=new Map<string,Report[]>(); reports.forEach(r=>{const k=`${Math.floor(r.lat/cell)}:${Math.floor(r.lng/cell)}`; map.set(k,[...(map.get(k)||[]),r])}); return [...map.values()].map(rs=>{const severity=rs.reduce((best,r)=>['PASSABLE','MINOR','MODERATE','SEVERE'].indexOf(r.severity)>['PASSABLE','MINOR','MODERATE','SEVERE'].indexOf(best)?r.severity:best,'PASSABLE' as Severity); const status=rs.some(r=>r.status==='CONFIRMED')?'CONFIRMED':rs.some(r=>r.status==='UNDER_REVIEW')?'UNDER_REVIEW':'UNVERIFIED'; return {lat:rs.reduce((a,r)=>a+r.lat,0)/rs.length,lng:rs.reduce((a,r)=>a+r.lng,0)/rs.length,reportCount:rs.length,aggregateSeverity:severity,aggregateConfidence:rs.reduce((a,r)=>a+r.confidence,0)/rs.length,highestStatus:status,memberIds:rs.map(r=>r.id)}})}
